version: '3.8'
services:
  postgres_develop:
    container_name: 'postgres_develop'
    platform: linux/x86_64
    image: postgres:15.1-alpine
    environment:
      POSTGRES_PASSWORD: "123456"
      POSTGRES_USER: "postgres_develop"
      POSTGRES_DB: "postgres_develop"
    ports:
      - "5435:5432"
