package main

const tmpl = `// Package {{.PackageName}}
// Autogenerated 
// DO NOT EDIT
package {{.PackageName}}

import "github.com/spf13/viper"

var environment map[string]string

func init() {

    environment = make(map[string]string)

    viper.AllowEmptyEnv(false)
    viper.SetEnvPrefix("{{.Runtime.EnvPrefix}}")
{{range $envVarName, $default := (.Runtime).EnvVariables}}    viper.MustBindEnv("{{$envVarName}}")
    viper.SetDefault("{{$envVarName}}", "{{$default}}")
{{end}}
}

// Get get environment variable.
func Get(name string) (env string) {

	if val, ok := environment[name]; ok {
		env = val
		return
	}

	env = viper.GetString(name)

	environment[name] = env

	return
    
}
`
