// Package conf
// Autogenerated
// DO NOT EDIT
package conf

import "github.com/spf13/viper"

var environment map[string]string

func init() {

	environment = make(map[string]string)

	viper.AllowEmptyEnv(false)
	viper.SetEnvPrefix("DB_EXTRACTOR")
	viper.MustBindEnv("DESTINATION_DB")
	viper.SetDefault("DESTINATION_DB", "postgres://postgres_develop:123456@localhost:5435/postgres_develop")
	viper.MustBindEnv("LIMIT")
	viper.SetDefault("LIMIT", "100")
	viper.MustBindEnv("SOURCE_DB")
	viper.SetDefault("SOURCE_DB", "postgres://develop_ds3_designshop3:JrEI364xmhgU@develop-ds3-designshop3-postgres.cemhcbawfahl.us-west-2.rds.amazonaws.com:5432/develop_ds3_designshop3")

}

// Get get environment variable.
func Get(name string) (env string) {

	if val, ok := environment[name]; ok {
		env = val
		return
	}

	env = viper.GetString(name)

	environment[name] = env

	return

}
